{"uid":"1dc07602aba043b1","name":"An RTP is sent through POSTE API","fullName":"tests.test_debtor_service_provider_availability#test_send_rtp_to_poste","historyId":"9ee43ed2ff7f9ef504e1b4a4edc013a4","time":{"start":1750777965692,"stop":1750777965693,"duration":1},"status":"broken","statusMessage":"OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem","statusTrace":"@allure.feature('RTP Send')\n    @allure.story('Service provider sends an RTP to POSTE directly')\n    @allure.title('An RTP is sent through POSTE API')\n    @pytest.mark.send\n    @pytest.mark.happy_path\n    @pytest.mark.poste\n    def test_send_rtp_to_poste():\n        rtp_data = generate_rtp_data()\n        cbi_payload = generate_cbi_rtp_data(rtp_data)\n    \n>       response = send_srtp_to_poste(cbi_payload)\n\nfunctional-tests/tests/test_debtor_service_provider_availability.py:120: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi/debtor_service_provider.py:21: in send_srtp_to_poste\n    return requests.post(\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/adapters.py:639: in send\n    self.cert_verify(conn, request.url, verify, cert)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <requests.adapters.HTTPAdapter object at 0x7f961c6d6bd0>\nconn = <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f961d9e2ea0>\nurl = 'https://rtp.coll.poste.it:446/iso20022/api/v1/sepa-request-to-pay-requests'\nverify = True\ncert = ('/home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem', '/home/runner/work/rtp-platform-qa/rtp-platform-qa/config/key.pem')\n\n    def cert_verify(self, conn, url, verify, cert):\n        \"\"\"Verify a SSL certificate. This method should not be called from user\n        code, and is only exposed for use when subclassing the\n        :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.\n    \n        :param conn: The urllib3 connection object associated with the cert.\n        :param url: The requested URL.\n        :param verify: Either a boolean, in which case it controls whether we verify\n            the server's TLS certificate, or a string, in which case it must be a path\n            to a CA bundle to use\n        :param cert: The SSL certificate to verify.\n        \"\"\"\n        if url.lower().startswith(\"https\") and verify:\n            conn.cert_reqs = \"CERT_REQUIRED\"\n    \n            # Only load the CA certificates if 'verify' is a string indicating the CA bundle to use.\n            # Otherwise, if verify is a boolean, we don't load anything since\n            # the connection will be using a context with the default certificates already loaded,\n            # and this avoids a call to the slow load_verify_locations()\n            if verify is not True:\n                # `verify` must be a str with a path then\n                cert_loc = verify\n    \n                if not os.path.exists(cert_loc):\n                    raise OSError(\n                        f\"Could not find a suitable TLS CA certificate bundle, \"\n                        f\"invalid path: {cert_loc}\"\n                    )\n    \n                if not os.path.isdir(cert_loc):\n                    conn.ca_certs = cert_loc\n                else:\n                    conn.ca_cert_dir = cert_loc\n        else:\n            conn.cert_reqs = \"CERT_NONE\"\n            conn.ca_certs = None\n            conn.ca_cert_dir = None\n    \n        if cert:\n            if not isinstance(cert, basestring):\n                conn.cert_file = cert[0]\n                conn.key_file = cert[1]\n            else:\n                conn.cert_file = cert\n                conn.key_file = None\n            if conn.cert_file and not os.path.exists(conn.cert_file):\n>               raise OSError(\n                    f\"Could not find the TLS certificate file, \"\n                    f\"invalid path: {conn.cert_file}\"\n                )\nE               OSError: Could not find the TLS certificate file, invalid path: /home/runner/work/rtp-platform-qa/rtp-platform-qa/config/cert.pem\n\n/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/requests/adapters.py:350: OSError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1750777957420,"stop":1750777957482,"duration":62},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"story","value":"Service provider sends an RTP to POSTE directly"},{"name":"feature","value":"RTP Send"},{"name":"tag","value":"poste"},{"name":"tag","value":"happy_path"},{"name":"tag","value":"send"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_debtor_service_provider_availability"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2232-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_debtor_service_provider_availability"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":52,"skipped":0,"passed":0,"unknown":0,"total":52},"items":[{"uid":"dc84809653bf1532","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/404//#testresult/dc84809653bf1532","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7895132e90>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750756725988,"stop":1750756860224,"duration":134236}},{"uid":"970bf40937eea695","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/403//#testresult/970bf40937eea695","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fd1c0c560d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750748875725,"stop":1750749009662,"duration":133937}},{"uid":"6f0f6b4e520793f6","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/402//#testresult/6f0f6b4e520793f6","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7e56c2e0d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750684871241,"stop":1750685007600,"duration":136359}},{"uid":"57a799f2d9f4bee9","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/401//#testresult/57a799f2d9f4bee9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f340528f250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750662510703,"stop":1750662646306,"duration":135603}},{"uid":"40885e7ced652fc9","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/400//#testresult/40885e7ced652fc9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f920765a0d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750576084541,"stop":1750576220836,"duration":136295}},{"uid":"257cdf92bb30591c","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/399//#testresult/257cdf92bb30591c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f99b804f250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750489651935,"stop":1750489787142,"duration":135207}},{"uid":"bdc87548abc6f41b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/398//#testresult/bdc87548abc6f41b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f49405ef250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750403245452,"stop":1750403381968,"duration":136516}},{"uid":"957d47383e84a297","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/397//#testresult/957d47383e84a297","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4b15363250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750335017992,"stop":1750335154023,"duration":136031}},{"uid":"b9d30daf6e270050","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/396//#testresult/b9d30daf6e270050","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fef93a720d0>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750329658096,"stop":1750329794563,"duration":136467}},{"uid":"99dc5542721f8c6","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/395//#testresult/99dc5542721f8c6","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fdb8b523610>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750328594285,"stop":1750328728602,"duration":134317}},{"uid":"9138498fa233ff77","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/394//#testresult/9138498fa233ff77","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff1ed2f3250>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750317554072,"stop":1750317689390,"duration":135318}},{"uid":"76a40a53b6c77ef8","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/393//#testresult/76a40a53b6c77ef8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0156e7610>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750316879510,"stop":1750317015794,"duration":136284}},{"uid":"60be80cdee5c3d4b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/392//#testresult/60be80cdee5c3d4b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f06a5323610>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750230495644,"stop":1750230630050,"duration":134406}},{"uid":"95818c65354b5941","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/391//#testresult/95818c65354b5941","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc68a027610>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750170145671,"stop":1750170281368,"duration":135697}},{"uid":"d1847462de7055f7","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/389//#testresult/d1847462de7055f7","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1c28c21e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750144060530,"stop":1750144194619,"duration":134089}},{"uid":"7d5c488b42c2200c","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/388//#testresult/7d5c488b42c2200c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb450c71e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750069041591,"stop":1750069176422,"duration":134831}},{"uid":"261e97bb74efa757","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/387//#testresult/261e97bb74efa757","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ffa5a9dde50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1750057721785,"stop":1750057858084,"duration":136299}},{"uid":"e8fa65034dfac89b","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/386//#testresult/e8fa65034dfac89b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0147051e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749971259479,"stop":1749971395917,"duration":136438}},{"uid":"d7cfd2080d86185c","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/385//#testresult/d7cfd2080d86185c","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3cac329e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749884865400,"stop":1749885000960,"duration":135560}},{"uid":"d9c517af71c13ea3","reportUrl":"https://pagopa.github.io/rtp-platform-qa/functional/384//#testresult/d9c517af71c13ea3","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='rtp.coll.poste.it', port=446): Max retries exceeded with url: /iso20022/api/v1/sepa-request-to-pay-requests (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0319e5e50>, 'Connection to rtp.coll.poste.it timed out. (connect timeout=5000)'))","time":{"start":1749810131834,"stop":1749810264856,"duration":133022}}]},"tags":["poste","send","happy_path"]},"source":"1dc07602aba043b1.json","parameterValues":[]}